tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "khushrajrathod/teledrive"
brew "apktool"
brew "openssl@1.1"
brew "glib"
brew "cmake"
brew "coreutils"
brew "cowsay"
brew "ffmpeg"
brew "ffsend"
brew "fontforge"
brew "git-lfs"
brew "gnupg", link: false
brew "gperf"
brew "node"
brew "http-server"
brew "imagemagick"
brew "jq"
brew "mas"
brew "meson"
brew "nativefier"
brew "qemu"
brew "rename"
brew "shellcheck"
brew "snapcraft"
brew "tree"
brew "wget"
brew "yarn"
brew "youtube-dl"
cask "adoptopenjdk"
cask "amazon-music"
cask "android-platform-tools"
cask "appcleaner"
cask "background-music"
cask "balenaetcher"
cask "bitwarden"
cask "bootstrap-studio"
cask "calibre"
cask "firefox-developer-edition"
cask "flashforge-flashprint"
cask "gitkraken"
cask "google-backup-and-sync"
cask "google-chrome"
cask "gpg-suite-no-mail"
cask "handbrake"
cask "hyper"
cask "iina"
cask "keka"
cask "maccy"
cask "mos"
cask "qbittorrent"
cask "rectangle"
cask "soundflower"
cask "telegram"
cask "tor-browser"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "vnc-viewer"
cask "zoomus"
mas "Bandwidth+", id: 490461369
mas "Dato", id: 1470584107
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Unsplash Wallpapers", id: 1284863847
mas "Xcode", id: 497799835
